INSERT IGNORE INTO settings (setting_title,setting_label,setting_value,setting_group,setting_type,is_secret,sort_order) VALUES
('SMTP protocol','MAIL_PROTOCOL','smtp','mail','text',0,10),
('SMTP host','MAIL_SMTP_HOST','mail.brickstory.com','mail','text',0,20),
('SMTP port','MAIL_SMTP_PORT','465','mail','number',0,30),
('SMTP encryption','MAIL_SMTP_CRYPTO','ssl','mail','text',0,40),
('SMTP username','MAIL_SMTP_USER','no-reply@brickstory.com','mail','email',0,50),
('SMTP password','MAIL_SMTP_PASS','','mail','password',1,60),
('From email','MAIL_FROM_EMAIL','admin@brickstory.com','mail','email',0,70),
('From name','MAIL_FROM_NAME','BrickStory','mail','text',0,80),
('Contact-us recipient','MAIL_CONTACT_RECIPIENT','admin@brickstory.com','mail','email',0,90),
('Twilio Account SID','SMS_TWILIO_SID','','sms','text',1,10),
('Twilio Auth Token','SMS_TWILIO_TOKEN','','sms','password',1,20),
('Twilio From Number','SMS_TWILIO_FROM','','sms','text',0,30),
('Daily SMS limit per phone','SMS_DAILY_LIMIT_PER_PHONE','5','sms','number',0,40),
('Google Maps Frontend Key','MAPS_FRONTEND_KEY','','maps','text',0,10),
('Google Maps Backend (Geocoding) Key','MAPS_BACKEND_KEY','','maps','password',1,20),
('Default map latitude','MAPS_DEFAULT_LAT','39.8283','maps','text',0,30),
('Default map longitude','MAPS_DEFAULT_LNG','-98.5795','maps','text',0,40),
('Default map zoom','MAPS_DEFAULT_ZOOM','4','maps','number',0,50);
